### PR TITLE
CI: banish USE_PYTEST env (as we always use pytest now)

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by NelleV** [comment]
I would be happy to include this change, but USE_PYTEST now refers on whether we launch the tests through py.test or through python tests.py (if USE_PYTEST==false). Are you still in favor of including this patch?

(I am in favor of including this patch…)

**Comment by NelleV** [comment]
let's always use python tests.py everywhere.

**Comment by NelleV** [comment]
oh no… you deleted the branch and I overwrote on my remote branch /o\.
I'll reimplement this patch.

**Comment by tacaswell** [comment]
Sorry, I am try to be aggressive about cleaning up old branches (and still end up with more branches than I remember working on...)

**Comment by NelleV** [comment]
well, I just reimplemented… but that taught me I should really fetch as soon as I merge.

**Pull request merged**
